### ISSUE TITLE
Add E-Invoicing features for the contact (buyerReference and governmentAgency)

### ISSUE THREAD

**Issue by jp-performance** [nico-kow/n8n-nodes-sevdesk#1]
Duplicates 👀
I have searched the existing issues

Latest version 📆
I have tested the latest version

Summary 💡
Sevdesk now provides two new options for their contact object enabling e-invoicing features. The newly added keys are "buyerReference" and "governmentAgency".

Examples 🫣
See sevdesk api docs under "Create a new contact" (https://api.sevdesk.de/#tag/Contact/operation/createContact) as well as "Update contact" (https://api.sevdesk.de/#tag/Contact/operation/updateContact).

Motivation 🔦
I want to be able to properly sync my contacts via n8n with data needed for e-invoicing.

**Comment by nico-kow** [comment]
Hey @jp-performance,
thanks for reaching out. Currently I am not not able to update the node because I don't have some spare time. I might post a template with sevdesk http nodes as building blocks. I will include the e invoice functionality then. But this could also take some time. You could also try to update the cantact with the simple http node and the sevdesk credential

**Comment by jp-performance** [comment]
This would be awesome!
Until then I do live with the simple http node "workaround" ;)
